# Site settings
title: LatexColab
description: Collaborative LaTeX Agent
url: https://acarmi.github.io/LatexColab

# Theme settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Custom variables for dark theme
github:
  is_project_page: true
  repository_url: https://github.com/acarmi/LatexColab

# Team repositories
repositories:
  main:
    name: LatexColab
    url: https://github.com/acarmi/LatexColab
    description: Original LaTeX collaboration tool
  extension:
    name: LatexColabHosted
    url: https://github.com/arikanev/LatexColabHosted
    description: Server-based extension by Ariel Kanevsky

# Build settings
markdown: kramdown